additionalProperties:
  apiPackage: com.ecommerce.products.infrastructure.rest
  modelPackage: com.ecommerce.products.domain.model
  invokerPackage: com.ecommerce.products
  dateLibrary: java8
  hideGenerationTimestamp: true
  groupId: com.ecommerce
  artifactId: products