CREATE TABLE IF NOT EXISTS PRICES (
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT,
    PRIORITY INTEGER,
    PRICE DECIMAL(10, 2),
    CURR VARCHAR(255)
);